### ISSUE TITLE
no blur

### ISSUE THREAD

**Issue by mennovanhout** [Zachariah-Abraham/glass#4] opened 2023-11-08 20:57 UTC
the blur doesn't work?
its a container with asblur inside a container with boxdecoration image:
![image](https://github.com/Zachariah-Abraham/glass/assets/26040589/d01caff5-d8b0-4c9f-b654-56870ebf1d13)

**Comment by Zachariah-Abraham** [comment] 2024-02-14 08:51
Hi @mennovanhout 
Are you still facing this issue? If so, could you provide an MRE?

**Comment by mennovanhout** [comment] 2024-02-14 08:53
> Hi @mennovanhout 
> Are you still facing this issue? If so, could you provide an MRE?

Yes sadly, what is an MRE? 😅

**Comment by Zachariah-Abraham** [comment] 2024-05-06 18:25
Hi @mennovanhout, an MRE is an Minimal Reproducible Example. A short snippet of code that runs the app and shows the issue.

**Comment by Zachariah-Abraham** [comment] 2024-11-17 09:54
Closing due to lack of information. Will reopen if there's an MRE.

**Closed as not planned by Zachariah-Abraham** 2024-11-17 09:54 UTC
